# Generated by Django 2.2.7 on 2020-01-01 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
